-- Create ETL Warehouse
CREATE OR REPLACE WAREHOUSE RETAIL_ETL_WH
WITH
WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for Retail ETL Pipeline';
 
-- Activate it
USE WAREHOUSE RETAIL_ETL_WH;

-- create three databases one for each layer
CREATE OR REPLACE DATABASE RETAIL_LANDING
COMMENT='Landing Zone';

CREATE OR REPLACE DATABASE RETAIL_CURATED
COMMENT='Curated Zone';

CREATE OR REPLACE DATABASE RETAIL_CONSUMPTION
COMMENT='Consumption Zone';

-- create three schema one for each layer
USE DATABASE RETAIL_LANDING;
CREATE OR REPLACE SCHEMA RAW;
  
USE DATABASE RETAIL_CURATED;
CREATE OR REPLACE SCHEMA CURATED;
 
USE DATABASE RETAIL_CONSUMPTION;
CREATE OR REPLACE SCHEMA MART;