-- Create the storage integration
CREATE STORAGE INTEGRATION RETAIL_S3_INT 
TYPE = EXTERNAL_STAGE  
STORAGE_PROVIDER = S3  
ENABLED = TRUE  
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::824939473734:role/SnowflakePipeS3ReadWriteRole'
STORAGE_ALLOWED_LOCATIONS = ('s3://rukky-retail-snowflake/raw/');
 
-- Get the snowflake identity
DESC STORAGE INTEGRATION RETAIL_S3_INT;

-- Create the File Format
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', '');

-- Create the stage
CREATE STAGE RETAIL_STAGE 
URL='s3://rukky-retail-snowflake/raw/' 
STORAGE_INTEGRATION = RETAIL_S3_INT 
FILE_FORMAT = CSV_FILE_FORMAT;
 
LIST @RETAIL_STAGE;

DESC PIPE SALES_PIPE;
 
DESC PIPE PRODUCT_PIPE;
 
ALTER PIPE SALES_PIPE REFRESH;
ALTER PIPE PRODUCT_PIPE REFRESH;
ALTER PIPE CUSTOMER_PIPE REFRESH;
 
select * from SALES_RAW limit 5;
select * from PRODUCT_RAW limit 5;
select * from CUSTOMER_RAW limit 5;
